### ISSUE TITLE
jars requeridos para buildear

### ISSUE THREAD

**Issue by eridal** [111milprogramadores/CertificacionInstructores#1]
Hola a todos,

Me encuentro intentando buildear el proyecto y no encuentro los jars necesarios para que el proyecto compile.

Hay alguna tarea ant o similar para bajarlos? Hay algun archivo de configuracion que liste los jars y sus versiones usadas?

Muchas gracias!

**Comment by eridal** [comment]
Lo que pude encontrar es este listado: https://github.com/111milprogramadores/CertificacionInstructores/blob/master/nbproject/project.properties#L32..46

**Comment by eridal** [comment]
A continuacion las URLs de los JARs necesarios para que el proyecto compile. 

- antlr-2.7.7.jar: http://central.maven.org/maven2/antlr/antlr/2.7.7/antlr-2.7.7.jar
- classmate-1.3.0.jar: http://central.maven.org/maven2/com/fasterxml/classmate/1.3.0/classmate-1.3.0.jar
- commons-beanutils-1.9.3.jar: http://central.maven.org/maven2/commons-beanutils/commons-beanutils/1.9.3/commons-beanutils-1.9.3.jar
- commons-collections-3.2.2.jar: http://central.maven.org/maven2/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2.jar
- commons-digester-2.1.jar: http://central.maven.org/maven2/commons-digester/commons-digester/2.1/commons-digester-2.1.jar
- commons-logging-1.2.jar: http://central.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
- dom4j-1.6.1.jar: http://central.maven.org/maven2/dom4j/dom4j/1.6.1/dom4j-1.6.1.jar
- hibernate-commons-annotations-5.0.1.Final.jar: http://central.maven.org/maven2/org/hibernate/common/hibernate-commons-annotations/5.0.0.Final/hibernate-commons-annotations-5.0.0.Final.jar
- hibernate-core-5.2.10.Final.jar: http://central.maven.org/maven2/org/hibernate/hibernate-core/5.2.10.Final/hibernate-core-5.2.10.Final.jar
- hibernate-jpa-2.1-api-1.0.0.Final.jar: http://central.maven.org/maven2/org/hibernate/javax/persistence/hibernate-jpa-2.1-api/1.0.0.Final/hibernate-jpa-2.1-api-1.0.0.Final.jar
- jandex-2.0.3.Final.jar: http://central.maven.org/maven2/org/jboss/jandex/2.0.3.Final/jandex-2.0.3.Final.jar
- jasperreports-6.4.1.jar: http://central.maven.org/maven2/net/sf/jasperreports/jasperreports/6.4.1/jasperreports-6.4.1.jar
- javassist-3.20.0-GA.jar: http://central.maven.org/maven2/org/javassist/javassist/3.20.0-GA/javassist-3.20.0-GA.jar
- jboss-logging-3.3.0.Final.jar: http://central.maven.org/maven2/org/jboss/logging/jboss-logging/3.3.0.Final/jboss-logging-3.3.0.Final.jar
- jboss-transaction-api_1.2_spec-1.0.1.Final.jar: http://central.maven.org/maven2/org/jboss/spec/javax/transaction/jboss-transaction-api_1.2_spec/1.0.1.Final/jboss-transaction-api_1.2_spec-1.0.1.Final.jar

**Comment by joarobles** [comment]
Estimado gracias por el comentario, 
Podrías hacer un Pull Request con las librerías agregadas así incorporamos tu aporte?

**Comment by eridal** [comment]
Al parecer Github tiene algun problema con la UI y no funcionan los dropdowns, ni los botones. Veo la animacion del click pero nada ocurre.


Hice el commit con los jars (https://github.com/eridal/CertificacionInstructores/commit/0ccd98c60d557dc6eadd86ff03644b6bcc8f4c4b) pero Github no me permite crear el PR.

Se me ocurren dos alternativas:

1. Que alguien mas cree el PR desde este mismo repositorio (pro: facil, con: github podria tambien fallar)

2. Que alguien con permiso de escritura en este repo haga pull + push (pro: seguro funciona, con: mayor complejidad)

**Comment by joarobles** [comment]
Acabo de ver el commit mencionado y parece estar OK,
Sería bueno si pudieras probar realizar el PR desde otra PC,
Espero tus comentarios!

**Comment by joarobles** [comment]
Solucionado en #3
